//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EventManagerPro.DBLayer
{
    public partial class Budget
    {
        public Budget()
        {
            this.BudgetItems = new HashSet<BudgetItem>();
        }
    
        public int Id { get; set; }
        public int AllocatedBudget { get; set; }
    
        public virtual ICollection<BudgetItem> BudgetItems { get; set; }
    }
    
}
